baseURL = "https://imissmyselfer.netlify.app/"
languageCode = "zh-tw"
title = "位元日報 Bit Daily"
theme = "ananke"
defaultContentLanguage = "zh-tw"

[params]
  description = "每天一點位元，掌握世界脈動"
  show_reading_time = true
